# Generated by Django 4.2.11 on 2024-10-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
    ]
