# Generated by Django 4.2.11 on 2024-10-09 20:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_deudas_id_remove_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('client', 'client'), ('agent', 'agent')], max_length=12, null=True),
        ),
    ]
