# Generated by Django 4.2.11 on 2024-10-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_message_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sentAt',
            field=models.DateTimeField(),
        ),
    ]
