# Generated by Django 4.2.11 on 2024-10-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_alter_deudas_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deudas',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='clients.client'),
        ),
    ]
